#创建数据库
CREATE DATABASE IF NOT EXISTS sdp_mobile;
#使用数据库
USE sdp_mobile;
#创建用户表
CREATE TABLE IF NOT EXISTS sdp_mobile_user (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '用户主键',
  account VARCHAR(30) NOT NULL DEFAULT '' COMMENT '账号' UNIQUE,
  password VARCHAR(30) NOT NULL DEFAULT '' COMMENT '密码',
  createtime INT NOT NULL DEFAULT 0 COMMENT '创建时间'
)
ENGINE MYISAM DEFAULT CHARSET=UTF8;
#创建登录日志表
CREATE TABLE IF NOT EXISTS sdp_mobile_login_log (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '登录日志',
  user_id INT NOT NULL DEFAULT 0 COMMENT '登录用户ID',
  logintime INT NOT NULL DEFAULT 0 COMMENT '登录时间'
)
ENGINE MYISAM DEFAULT CHARSET=UTF8;
#创建应用列表
CREATE TABLE IF NOT EXISTS  sdp_mobile_application (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '应用主键',
  appname VARCHAR(50) NOT NULL DEFAULT '' COMMENT '应用名称' UNIQUE,
  access_key_id VARCHAR(50) NOT NULL DEFAULT '' COMMENT '验证KEYID',
  access_key_secret VARCHAR(50) NOT NULL DEFAULT '' COMMENT '验证secret',
  appkey VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'appkey',
  user_id INT NOT NULL DEFAULT 0 COMMENT '创建的用户ID',
  createtime INT NOT NULL DEFAULT 0 COMMENT '创建时间'
)
ENGINE MYISAM DEFAULT CHARSET=UTF8;